version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    image: node:22
    working_dir: /app
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URL=mongodb://mongo:27017/moodtrackr
    volumes:
      - ./moodtrackr-server:/app
    command: bash -lc "npm ci && npm start"
    depends_on:
      - mongo

volumes:
  mongo_data:
